"""make event date not nullable

Revision ID: 3a0a3dfa6a2b
Revises: 53a580894191
Create Date: 2025-01-24 14:08:23.147631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0a3dfa6a2b'
down_revision: Union[str, None] = '53a580894191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'event_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'event_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
