"""Add brs_id to curr_unit

Revision ID: 4f118edeb775
Revises: 05e8b7414130
Create Date: 2025-04-05 00:08:06.472169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f118edeb775'
down_revision: Union[str, None] = '05e8b7414130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_units', sa.Column('brs_id', sa.Integer(), nullable=True))
    op.execute("UPDATE curriculum_units SET brs_id = 0")
    op.alter_column('curriculum_units', 'brs_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_units', 'brs_id')
    # ### end Alembic commands ###
