"""article id fixed 2

Revision ID: 531a64b95705
Revises: 46e73e9c342e
Create Date: 2025-01-19 20:57:22.697955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531a64b95705'
down_revision: Union[str, None] = '46e73e9c342e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE articles ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE articles ALTER COLUMN id DROP IDENTITY;")
    # ### end Alembic commands ###
