"""event date added null

Revision ID: 602e8e6cba0a
Revises: 531a64b95705
Create Date: 2025-01-24 13:59:44.332381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602e8e6cba0a'
down_revision: Union[str, None] = '531a64b95705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('event_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'event_date')
    # ### end Alembic commands ###
