"""add article_tag_association table

Revision ID: 775bd3da4148
Revises: 6cf4d3fb25b8
Create Date: 2025-05-10 16:38:14.507388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775bd3da4148'
down_revision: Union[str, None] = '6cf4d3fb25b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('articles_tag_id_fkey', 'articles', type_='foreignkey')
    op.drop_column('articles', 'tag_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('articles_tag_id_fkey', 'articles', 'tags', ['tag_id'], ['id'])
    op.drop_table('article_tag_association')
    # ### end Alembic commands ###
