"""Add new tables

Revision ID: 79e030ec5aac
Revises: df417040438f
Create Date: 2025-04-04 21:32:24.366492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e030ec5aac'
down_revision: Union[str, None] = 'df417040438f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practice_teacher_brs_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('stud_group_brs_id', sa.Integer(), nullable=False),
    sa.Column('teacher_brs_id', sa.Integer(), nullable=False),
    sa.Column('subject_brs_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stud_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brs_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brs_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('stud_groups')
    op.drop_table('curriculum_units')
    # ### end Alembic commands ###
