"""added icon for teachers

Revision ID: d3a0283e2206
Revises: 775bd3da4148
Create Date: 2025-05-29 00:48:52.691498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a0283e2206'
down_revision: Union[str, None] = '775bd3da4148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'icon')
    # ### end Alembic commands ###
