"""Add brs_id to teachers

Revision ID: df417040438f
Revises: 3a0a3dfa6a2b
Create Date: 2025-04-04 21:13:12.376969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df417040438f'
down_revision: Union[str, None] = '3a0a3dfa6a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку с nullable=True
    op.add_column('teachers', sa.Column('brs_id', sa.Integer(), nullable=True))
    # 2. Заполняем чем-то (например, временно нулями)
    op.execute("UPDATE teachers SET brs_id = 0")  # или другое дефолтное значение
    # 3. Делаем колонку NOT NULL
    op.alter_column('teachers', 'brs_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'brs_id')
    # ### end Alembic commands ###
