"""Add timezone

Revision ID: e0e9d871957b
Revises: 12fbdca7a2aa
Create Date: 2025-01-19 20:10:07.508893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e9d871957b'
down_revision: Union[str, None] = '12fbdca7a2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
