"""add teacher_curriculum_unit_link table

Revision ID: eeb8655b0a44
Revises: 4f118edeb775
Create Date: 2025-05-05 23:55:54.740915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb8655b0a44'
down_revision: Union[str, None] = '4f118edeb775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_curriculum_unit_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_unit_id', sa.Integer(), nullable=False),
    sa.Column('is_practice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_unit_id'], ['curriculum_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_curriculum_unit_link')
    # ### end Alembic commands ###
